FROM golang:1.23.1-alpine AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY ./seeder ./seeder
COPY wait-for-it.sh .
RUN chmod +x wait-for-it.sh

CMD ["go", "run", "./seeder/main.go"]