name: Dev Branch CI

on:
  push:
    branches:
      - dev
      
  pull_request:
    branches:
      - dev  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2

      - name: Install Dependencies
        run: go mod download

      - name: Run Linting
        run: golangci-lint run

      - name: Run Unit Tests
        run: go test ./...

      - name: Run Integration Tests
        run: go test -tags=integration ./...

      - name: Build application
        run: go build -v ./...